version: 2.1

orbs:
  node: circleci/node@4.7
  codecov: codecov/codecov@3.2.5

jobs:
  build-test-coverage:
    docker:
      - image: cimg/node:20.16.0-browsers

    steps:
      - checkout
      - run: npm ci
      - run: npm run test
      - codecov/upload:
          file: ./coverage/lcov.info

workflows:
  build-test-coverage:
    jobs:
      - build-test-coverage
