version: 2.1

orbs:
  node: circleci/node@4.7
  codecov: codecov/codecov@3.2.5

jobs:
  build-test-coverage:
    docker:
      - image: cimg/node:16.10

    steps:
      - checkout
      
      - run:
          name: Install headless VSCode dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install -y libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev
            sudo apt-get install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libnss3 lsb-release xdg-utils wget ca-certificates
            sudo apt-get install xvfb x11-apps x11-xkb-utils libx11-6 libx11-xcb1
            Xvfb -ac :99 -screen 0 1280x1024x16 & export DISPLAY=:99

      - run:
          name: Install TypeScript
          command: npm install typescript --no-save

      - run:
          name: Install c8 package
          command: npm install --save-dev c8
          
      - run:
          name: Run Tests
          command: xvfb-run npm test

      - codecov/upload:
          file: ./coverage/lcov.info

workflows:
  build-test-coverage:
    jobs:
      - build-test-coverage
